# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nn_control.ui'
#
# Created by: PySide6 UI code generator (originally PyQt5) 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_nn_control(object):
    def setupUi(self, nn_control):
        nn_control.setObjectName("nn_control")
        nn_control.resize(400, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(nn_control.sizePolicy().hasHeightForWidth())
        nn_control.setSizePolicy(sizePolicy)
        self.main_layout = QtWidgets.QVBoxLayout(nn_control)
        self.main_layout.setContentsMargins(5, 5, 5, 5)
        self.main_layout.setSpacing(6)
        self.main_layout.setObjectName("main_layout")

        # GPU Status indicator label
        self.gpu_status_label = QtWidgets.QLabel(nn_control)
        self.gpu_status_label.setObjectName("gpu_status_label")
        font_status = QtGui.QFont()
        font_status.setBold(True)
        self.gpu_status_label.setFont(font_status)
        self.gpu_status_label.setMinimumHeight(22)
        self.main_layout.addWidget(self.gpu_status_label)

        self.enable_gpu_checkbox = QtWidgets.QCheckBox(nn_control)
        self.enable_gpu_checkbox.setChecked(True)
        self.enable_gpu_checkbox.setObjectName("enable_gpu_checkbox")
        self.main_layout.addWidget(self.enable_gpu_checkbox)
        # Two-column grid layout for training parameters
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")

        # Define expanding size policy for input widgets
        expandingSizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        expandingSizePolicy.setHorizontalStretch(0)
        expandingSizePolicy.setVerticalStretch(0)

        # Row 0: Batch Size | Learning Rate
        self.batch_size_label = QtWidgets.QLabel(nn_control)
        self.batch_size_label.setObjectName("batch_size_label")
        self.gridLayout.addWidget(self.batch_size_label, 0, 0)

        self.batch_size_spinbox = QtWidgets.QSpinBox(nn_control)
        self.batch_size_spinbox.setSizePolicy(expandingSizePolicy)
        self.batch_size_spinbox.setMinimum(1)
        self.batch_size_spinbox.setMaximum(999)
        self.batch_size_spinbox.setProperty("value", 16)
        self.batch_size_spinbox.setObjectName("batch_size_spinbox")
        self.gridLayout.addWidget(self.batch_size_spinbox, 0, 1)

        self.learning_rate_label = QtWidgets.QLabel(nn_control)
        self.learning_rate_label.setObjectName("learning_rate_label")
        self.gridLayout.addWidget(self.learning_rate_label, 0, 2)

        self.learning_rate_dspinbox = QtWidgets.QDoubleSpinBox(nn_control)
        self.learning_rate_dspinbox.setSizePolicy(expandingSizePolicy)
        self.learning_rate_dspinbox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.learning_rate_dspinbox.setDecimals(5)
        self.learning_rate_dspinbox.setMaximum(1.0)
        self.learning_rate_dspinbox.setSingleStep(0.0001)
        self.learning_rate_dspinbox.setProperty("value", 0.001)
        self.learning_rate_dspinbox.setObjectName("learning_rate_dspinbox")
        self.gridLayout.addWidget(self.learning_rate_dspinbox, 0, 3)

        # Row 1: Epochs | Weight Decay
        self.epochs_label = QtWidgets.QLabel(nn_control)
        self.epochs_label.setObjectName("epochs_label")
        self.gridLayout.addWidget(self.epochs_label, 1, 0)

        self.epochs_spinbox = QtWidgets.QSpinBox(nn_control)
        self.epochs_spinbox.setSizePolicy(expandingSizePolicy)
        self.epochs_spinbox.setMinimum(1)
        self.epochs_spinbox.setMaximum(999)
        self.epochs_spinbox.setProperty("value", 50)
        self.epochs_spinbox.setObjectName("epochs_spinbox")
        self.gridLayout.addWidget(self.epochs_spinbox, 1, 1)

        self.weight_decay_label = QtWidgets.QLabel(nn_control)
        self.weight_decay_label.setObjectName("weight_decay_label")
        self.gridLayout.addWidget(self.weight_decay_label, 1, 2)

        self.weight_decay_dspinbox = QtWidgets.QDoubleSpinBox(nn_control)
        self.weight_decay_dspinbox.setSizePolicy(expandingSizePolicy)
        self.weight_decay_dspinbox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.weight_decay_dspinbox.setDecimals(6)
        self.weight_decay_dspinbox.setMaximum(1.0)
        self.weight_decay_dspinbox.setSingleStep(0.00001)
        self.weight_decay_dspinbox.setProperty("value", 0.00001)
        self.weight_decay_dspinbox.setObjectName("weight_decay_dspinbox")
        self.gridLayout.addWidget(self.weight_decay_dspinbox, 1, 3)

        # Row 2: Dropout | Loss Function
        self.dropout_label = QtWidgets.QLabel(nn_control)
        self.dropout_label.setObjectName("dropout_label")
        self.gridLayout.addWidget(self.dropout_label, 2, 0)

        self.dropout_dspinbox = QtWidgets.QDoubleSpinBox(nn_control)
        self.dropout_dspinbox.setSizePolicy(expandingSizePolicy)
        self.dropout_dspinbox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.dropout_dspinbox.setDecimals(2)
        self.dropout_dspinbox.setMaximum(0.9)
        self.dropout_dspinbox.setSingleStep(0.05)
        self.dropout_dspinbox.setProperty("value", 0.0)
        self.dropout_dspinbox.setObjectName("dropout_dspinbox")
        self.gridLayout.addWidget(self.dropout_dspinbox, 2, 1)

        self.loss_function_label = QtWidgets.QLabel(nn_control)
        self.loss_function_label.setObjectName("loss_function_label")
        self.gridLayout.addWidget(self.loss_function_label, 2, 2)

        self.loss_function_combo = QtWidgets.QComboBox(nn_control)
        self.loss_function_combo.setSizePolicy(expandingSizePolicy)
        self.loss_function_combo.addItems(["MSE", "LPIPS", "PSNR", "SSIM", "Combined"])
        self.loss_function_combo.setObjectName("loss_function_combo")
        self.gridLayout.addWidget(self.loss_function_combo, 2, 3)

        # Row 3: Optimizer (left column only)
        self.optimizer_label = QtWidgets.QLabel(nn_control)
        self.optimizer_label.setObjectName("optimizer_label")
        self.gridLayout.addWidget(self.optimizer_label, 3, 0)

        self.optimizer_combo = QtWidgets.QComboBox(nn_control)
        self.optimizer_combo.setSizePolicy(expandingSizePolicy)
        self.optimizer_combo.addItems(["Adam", "AdamW", "SGD", "RMSprop"])
        self.optimizer_combo.setObjectName("optimizer_combo")
        self.gridLayout.addWidget(self.optimizer_combo, 3, 1)

        # Set column stretch to make both columns equal width
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(3, 1)

        self.main_layout.addLayout(self.gridLayout)
        self.train_button = QtWidgets.QPushButton(nn_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.train_button.sizePolicy().hasHeightForWidth())
        self.train_button.setSizePolicy(sizePolicy)
        self.train_button.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.train_button.setFont(font)
        self.train_button.setObjectName("train_button")
        self.main_layout.addWidget(self.train_button)

        self.retranslateUi(nn_control)
        QtCore.QMetaObject.connectSlotsByName(nn_control)

    def retranslateUi(self, nn_control):
        _translate = QtCore.QCoreApplication.translate
        nn_control.setWindowTitle(_translate("nn_control", "Form"))
        self.gpu_status_label.setText(_translate("nn_control", "GPU Status: Checking..."))
        self.enable_gpu_checkbox.setText(_translate("nn_control", "Enable GPU (CUDA)"))
        self.batch_size_label.setText(_translate("nn_control", "Batch Size"))
        self.learning_rate_label.setText(_translate("nn_control", "Learning Rate"))
        self.epochs_label.setText(_translate("nn_control", "Epochs"))
        self.weight_decay_label.setText(_translate("nn_control", "Weight Decay"))
        self.dropout_label.setText(_translate("nn_control", "Dropout"))
        self.loss_function_label.setText(_translate("nn_control", "Loss Function"))
        self.optimizer_label.setText(_translate("nn_control", "Optimizer"))
        self.train_button.setText(_translate("nn_control", "Train Model and Apply Post-processing"))
