# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/custom_widgets/mask_control/hadamard_control/ui_hadamard_control.ui'
#
# Created by: PySide6 UI code generator (originally PyQt5) 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Hadamard_Control(object):
    def setupUi(self, Hadamard_Control):
        Hadamard_Control.setObjectName("Hadamard_Control")
        Hadamard_Control.resize(498, 150)
        Hadamard_Control.setMinimumSize(QtCore.QSize(200, 100))
        self.main_layout = QtWidgets.QVBoxLayout(Hadamard_Control)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.Hadamard_form_layout = QtWidgets.QGridLayout()
        self.Hadamard_form_layout.setObjectName("Hadamard_form_layout")
        self.number_patterns_max_hadamard_info_text = QtWidgets.QLabel(Hadamard_Control)
        self.number_patterns_max_hadamard_info_text.setObjectName("number_patterns_max_hadamard_info_text")
        self.Hadamard_form_layout.addWidget(self.number_patterns_max_hadamard_info_text, 0, 0, 1, 1)
        self.number_patterns_max_hadamard_value = QtWidgets.QLabel(Hadamard_Control)
        self.number_patterns_max_hadamard_value.setText("")
        self.number_patterns_max_hadamard_value.setObjectName("number_patterns_max_hadamard_value")
        self.Hadamard_form_layout.addWidget(self.number_patterns_max_hadamard_value, 0, 1, 1, 1)
        self.range_patterns_hadamard_info_text = QtWidgets.QLabel(Hadamard_Control)
        self.range_patterns_hadamard_info_text.setObjectName("range_patterns_hadamard_info_text")
        self.Hadamard_form_layout.addWidget(self.range_patterns_hadamard_info_text, 0, 2, 1, 1)
        self.range_patterns_hadamard_value = QtWidgets.QLabel(Hadamard_Control)
        self.range_patterns_hadamard_value.setText("")
        self.range_patterns_hadamard_value.setObjectName("range_patterns_hadamard_value")
        self.Hadamard_form_layout.addWidget(self.range_patterns_hadamard_value, 0, 3, 1, 1)
        self.main_layout.addLayout(self.Hadamard_form_layout)
        self.hadamard_slider = QtWidgets.QSlider(Hadamard_Control)
        self.hadamard_slider.setOrientation(QtCore.Qt.Horizontal)
        self.hadamard_slider.setObjectName("hadamard_slider")
        self.main_layout.addWidget(self.hadamard_slider)
        self.generate_masks_button = QtWidgets.QPushButton(Hadamard_Control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generate_masks_button.sizePolicy().hasHeightForWidth())
        self.generate_masks_button.setSizePolicy(sizePolicy)
        self.generate_masks_button.setObjectName("generate_masks_button")
        self.main_layout.addWidget(self.generate_masks_button)

        self.retranslateUi(Hadamard_Control)
        QtCore.QMetaObject.connectSlotsByName(Hadamard_Control)

    def retranslateUi(self, Hadamard_Control):
        _translate = QtCore.QCoreApplication.translate
        Hadamard_Control.setWindowTitle(_translate("Hadamard_Control", "Form"))
        self.number_patterns_max_hadamard_info_text.setText(_translate("Hadamard_Control", "Max patterns number:"))
        self.range_patterns_hadamard_info_text.setText(_translate("Hadamard_Control", "Range:"))
        self.generate_masks_button.setText(_translate("Hadamard_Control", "Create masks"))
