# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/custom_widgets/mask_control/sweep_control/ui_sweep_control.ui'
#
# Created by: PySide6 UI code generator (originally PyQt5) 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Sweep_Control(object):
    def setupUi(self, Sweep_Control):
        Sweep_Control.setObjectName("Sweep_Control")
        Sweep_Control.resize(498, 180)
        Sweep_Control.setMinimumSize(QtCore.QSize(200, 100))
        self.main_layout = QtWidgets.QVBoxLayout(Sweep_Control)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setSpacing(5)
        self.main_layout.setObjectName("main_layout")
        self.table_buttons_layout = QtWidgets.QHBoxLayout()
        self.table_buttons_layout.setSpacing(5)
        self.table_buttons_layout.setObjectName("table_buttons_layout")
        self.sweep_parameters_table = QtWidgets.QTableWidget(Sweep_Control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.sweep_parameters_table.sizePolicy().hasHeightForWidth())
        self.sweep_parameters_table.setSizePolicy(sizePolicy)
        self.sweep_parameters_table.setMinimumSize(QtCore.QSize(0, 80))
        self.sweep_parameters_table.setRowCount(4)
        self.sweep_parameters_table.setColumnCount(3)
        self.sweep_parameters_table.setObjectName("sweep_parameters_table")
        item = QtWidgets.QTableWidgetItem()
        self.sweep_parameters_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sweep_parameters_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sweep_parameters_table.setHorizontalHeaderItem(2, item)
        self.table_buttons_layout.addWidget(self.sweep_parameters_table)
        self.buttons_layout = QtWidgets.QVBoxLayout()
        self.buttons_layout.setSpacing(3)
        self.buttons_layout.setObjectName("buttons_layout")
        self.add_row_button = QtWidgets.QPushButton(Sweep_Control)
        self.add_row_button.setMinimumSize(QtCore.QSize(28, 28))
        self.add_row_button.setMaximumSize(QtCore.QSize(28, 28))
        self.add_row_button.setObjectName("add_row_button")
        self.buttons_layout.addWidget(self.add_row_button)
        self.remove_row_button = QtWidgets.QPushButton(Sweep_Control)
        self.remove_row_button.setMinimumSize(QtCore.QSize(28, 28))
        self.remove_row_button.setMaximumSize(QtCore.QSize(28, 28))
        self.remove_row_button.setObjectName("remove_row_button")
        self.buttons_layout.addWidget(self.remove_row_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.buttons_layout.addItem(spacerItem)
        self.table_buttons_layout.addLayout(self.buttons_layout)
        self.main_layout.addLayout(self.table_buttons_layout)
        self.generate_masks_button = QtWidgets.QPushButton(Sweep_Control)
        font = QtGui.QFont()
        font.setKerning(True)
        self.generate_masks_button.setFont(font)
        self.generate_masks_button.setObjectName("generate_masks_button")
        self.main_layout.addWidget(self.generate_masks_button)

        self.retranslateUi(Sweep_Control)
        QtCore.QMetaObject.connectSlotsByName(Sweep_Control)

    def retranslateUi(self, Sweep_Control):
        _translate = QtCore.QCoreApplication.translate
        Sweep_Control.setWindowTitle(_translate("Sweep_Control", "Form"))
        item = self.sweep_parameters_table.horizontalHeaderItem(0)
        item.setText(_translate("Sweep_Control", "Angle"))
        item = self.sweep_parameters_table.horizontalHeaderItem(1)
        item.setText(_translate("Sweep_Control", "Bar Width"))
        item = self.sweep_parameters_table.horizontalHeaderItem(2)
        item.setText(_translate("Sweep_Control", "Stride"))
        self.add_row_button.setToolTip(_translate("Sweep_Control", "Add row"))
        self.add_row_button.setText(_translate("Sweep_Control", "+"))
        self.remove_row_button.setToolTip(_translate("Sweep_Control", "Remove selected row"))
        self.remove_row_button.setText(_translate("Sweep_Control", "−"))
        self.generate_masks_button.setText(_translate("Sweep_Control", "Create masks"))
