# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/custom_widgets/mask_control/scatter_control/ui_scatter_control.ui'
#
# Created by: PySide6 UI code generator (originally PyQt5) 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Scatter_Control(object):
    def setupUi(self, Scatter_Control):
        Scatter_Control.setObjectName("Scatter_Control")
        Scatter_Control.resize(498, 150)
        Scatter_Control.setMinimumSize(QtCore.QSize(200, 100))
        self.main_layout = QtWidgets.QVBoxLayout(Scatter_Control)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.Scatter_Grid_Layout = QtWidgets.QGridLayout()
        self.Scatter_Grid_Layout.setObjectName("Scatter_Grid_Layout")
        self.point_density_info_text = QtWidgets.QLabel(Scatter_Control)
        self.point_density_info_text.setObjectName("point_density_info_text")
        self.Scatter_Grid_Layout.addWidget(self.point_density_info_text, 0, 0, 1, 1)
        self.point_density_value = QtWidgets.QSpinBox(Scatter_Control)
        self.point_density_value.setAlignment(QtCore.Qt.AlignCenter)
        self.point_density_value.setMaximum(100)
        self.point_density_value.setSingleStep(1)
        self.point_density_value.setProperty("value", 10)
        self.point_density_value.setDisplayIntegerBase(10)
        self.point_density_value.setObjectName("point_density_value")
        self.Scatter_Grid_Layout.addWidget(self.point_density_value, 0, 1, 1, 1)
        self.random_seed_scatter_text = QtWidgets.QLabel(Scatter_Control)
        self.random_seed_scatter_text.setObjectName("random_seed_scatter_text")
        self.Scatter_Grid_Layout.addWidget(self.random_seed_scatter_text, 0, 2, 1, 1)
        self.random_seed_scatter_value = QtWidgets.QSpinBox(Scatter_Control)
        self.random_seed_scatter_value.setAlignment(QtCore.Qt.AlignCenter)
        self.random_seed_scatter_value.setMaximum(4096)
        self.random_seed_scatter_value.setSingleStep(1)
        self.random_seed_scatter_value.setProperty("value", 10)
        self.random_seed_scatter_value.setDisplayIntegerBase(10)
        self.random_seed_scatter_value.setObjectName("random_seed_scatter_value")
        self.Scatter_Grid_Layout.addWidget(self.random_seed_scatter_value, 0, 3, 1, 1)
        self.number_patterns_scatter_info_text = QtWidgets.QLabel(Scatter_Control)
        self.number_patterns_scatter_info_text.setObjectName("number_patterns_scatter_info_text")
        self.Scatter_Grid_Layout.addWidget(self.number_patterns_scatter_info_text, 1, 0, 1, 1)
        self.number_patterns_scatter_value = QtWidgets.QSpinBox(Scatter_Control)
        self.number_patterns_scatter_value.setAlignment(QtCore.Qt.AlignCenter)
        self.number_patterns_scatter_value.setMinimum(1)
        self.number_patterns_scatter_value.setMaximum(50000)
        self.number_patterns_scatter_value.setProperty("value", 1280)
        self.number_patterns_scatter_value.setObjectName("number_patterns_scatter_value")
        self.Scatter_Grid_Layout.addWidget(self.number_patterns_scatter_value, 1, 1, 1, 1)
        self.select_applicator_scatter_info_text = QtWidgets.QLabel(Scatter_Control)
        self.select_applicator_scatter_info_text.setObjectName("select_applicator_scatter_info_text")
        self.Scatter_Grid_Layout.addWidget(self.select_applicator_scatter_info_text, 1, 2, 1, 1)
        self.select_applicator_scatter_list = QtWidgets.QComboBox(Scatter_Control)
        self.select_applicator_scatter_list.setObjectName("select_applicator_scatter_list")
        self.select_applicator_scatter_list.addItem("")
        self.select_applicator_scatter_list.addItem("")
        self.select_applicator_scatter_list.addItem("")
        self.select_applicator_scatter_list.addItem("")
        self.Scatter_Grid_Layout.addWidget(self.select_applicator_scatter_list, 1, 3, 1, 1)
        self.main_layout.addLayout(self.Scatter_Grid_Layout)
        self.generate_masks_button = QtWidgets.QPushButton(Scatter_Control)
        font = QtGui.QFont()
        font.setKerning(True)
        self.generate_masks_button.setFont(font)
        self.generate_masks_button.setObjectName("generate_masks_button")
        self.main_layout.addWidget(self.generate_masks_button)

        self.retranslateUi(Scatter_Control)
        QtCore.QMetaObject.connectSlotsByName(Scatter_Control)

    def retranslateUi(self, Scatter_Control):
        _translate = QtCore.QCoreApplication.translate
        Scatter_Control.setWindowTitle(_translate("Scatter_Control", "Form"))
        self.point_density_info_text.setText(_translate("Scatter_Control", "Point density:"))
        self.random_seed_scatter_text.setText(_translate("Scatter_Control", "Random seed:"))
        self.number_patterns_scatter_info_text.setText(_translate("Scatter_Control", "Number of patterns:"))
        self.select_applicator_scatter_info_text.setText(_translate("Scatter_Control", "Reconstruction method:"))
        self.select_applicator_scatter_list.setItemText(0, _translate("Scatter_Control", "Ghost Imaging"))
        self.select_applicator_scatter_list.setItemText(1, _translate("Scatter_Control", "Pseudoinverse"))
        self.select_applicator_scatter_list.setItemText(2, _translate("Scatter_Control", "FISTA"))
        self.select_applicator_scatter_list.setItemText(3, _translate("Scatter_Control", "TV-norm"))
        self.generate_masks_button.setText(_translate("Scatter_Control", "Create masks"))
